apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-kong
  namespace: kong
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kong
  selector:
    matchLabels:
      app.kubernetes.io/instance: kong
      app.kubernetes.io/name: kong
      release: kong
  endpoints:
    - port: status
      path: /metrics
      interval: 30s
